export const dayList = [
  { id: 1, name: "Monday", shortName: "M", value: "mon", isSelected: false },
  {
    id: 2,
    name: "Tuesday",
    shortName: "T",
    value: "tue",
    isSelected: false,
  },
  {
    id: 3,
    name: "Wednesday",
    shortName: "W",
    value: "wen",
    isSelected: false,
  },
  {
    id: 4,
    name: "Thursday",
    shortName: "T",
    value: "thu",
    isSelected: false,
  },
  { id: 5, name: "Friday", shortName: "F", value: "fri", isSelected: false },
  {
    id: 6,
    name: "Saturday",
    shortName: "S",
    value: "sat",
    isSelected: false,
  },
  { id: 7, name: "Sunday", shortName: "S", value: "sun", isSelected: false },
];

export const conditionList = [
  { id: 1, name: "Ears", value: "Ears" },
  { id: 2, name: "Eye", value: "Eyes" },
  { id: 3, name: "Mouth", value: "Mouth" },
  { id: 4, name: "Gastrointestinal", value: "Gastrointestinal" },
  { id: 5, name: "Limping or mobility", value: "Mobility" },
  { id: 6, name: "Respiratory", value: "Respiratory" },
  { id: 7, name: "Skin & coat", value: "Skin" },
  { id: 8, name: "Urinary", value: "renalUrinary" },
  { id: 9, name: "Emergency", value: "Emergency" },
  { id: 10, name: "General", value: "General" },
];

export const clinicFilterList = [
  { name: "Clinic Name", value: "name" },
  { name: "Location", value: "location" },
];

export const scheduleList = [
  { name: "Schedule", value: "Pending" },
  { name: "Mark as Complete", value: "Completed" },
];

export const statusList = [
  { name: "All", value: "All" },
  { name: "Pending", value: "Pending" },
  { name: "Completed", value: "Completed" },
  { name: "Overdue", value: "Overdue" },
];

export const LocationList = [
  { name: "Adyar", value: "Adyar" },
  { name: "Guindy", value: "Guindy" },
];

export const diagnosticList = [
  { name: "Complete Blood Count (CBC)", value: "Complete Blood Count (CBC)" },
  {
    name: "Erythrocyte Sedimentation Rate (ESR)",
    value: "Erythrocyte Sedimentation Rate (ESR)",
  },
  { name: "Serum Biochemical Profile", value: "Serum Biochemical Profile" },
  { name: "Blood Urea Nitrogen (BUN)", value: "Blood Urea Nitrogen (BUN)" },
  { name: "Creatinine", value: "Creatinine" },
  {
    name: "Liver Enzymes (ALT, AST, ALP)",
    value: "Liver Enzymes (ALT, AST, ALP)",
  },
  { name: "Electrolytes", value: "Electrolytes" },
  { name: "Routine Urinalysis", value: "Routine Urinalysis" },
  {
    name: "Specific Tests (Protein, Glucose, etc.)",
    value: "Specific Tests (Protein, Glucose, etc.)",
  },
  { name: "Fecal Floatation", value: "Fecal Floatation" },
  { name: "Fecal Smear", value: "Fecal Smear" },
  { name: "Fecal Occult Blood Test", value: "Fecal Occult Blood Test" },
  {
    name: "Thyroid Function Tests (T4, T3)",
    value: "Thyroid Function Tests (T4, T3)",
  },
  { name: "Cortisol Tests", value: "Cortisol Tests" },
  { name: "ELISA", value: "ELISA" },
  { name: "PCR", value: "PCR" },
  { name: "Western Blot", value: "Western Blot" },
  {
    name: "X-rays, Ultrasound, MRI, CT Scan",
    value: "X-rays, Ultrasound, MRI, CT Scan",
  },
  {
    name: "Skin Scraping, Fine Needle Aspirate",
    value: "Skin Scraping, Fine Needle Aspirate",
  },
  { name: "Biopsy", value: "Biopsy" },
  { name: "Culture and Sensitivity", value: "Culture and Sensitivity" },
  { name: "Electrocardiogram (ECG)", value: "Electrocardiogram (ECG)" },
  { name: "Echocardiogram", value: "Echocardiogram" },
  { name: "Intradermal Skin Testing", value: "Intradermal Skin Testing" },
  { name: "Serum Allergy Testing", value: "Serum Allergy Testing" },
];

export const profileSettingsDays = [
  {
    i: 0,
    name: "Sunday",
    value: "sun",
    isSelected: false,
    startTime: new Date(),
    endTime: new Date(),
    duration: "15",
  },
  {
    i: 1,
    name: "Monday",
    value: "mon",
    isSelected: false,
    startTime: new Date(),
    endTime: new Date(),
    duration: "15",
  },
  {
    i: 2,
    name: "Tuesday",
    value: "tue",
    isSelected: false,
    startTime: new Date(),
    endTime: new Date(),
    duration: "15",
  },
  {
    i: 3,
    name: "Wednesday",
    value: "wen",
    isSelected: false,
    startTime: new Date(),
    endTime: new Date(),
    duration: "15",
  },
  {
    i: 4,
    name: "Thursday",
    value: "thu",
    isSelected: false,
    startTime: new Date(),
    endTime: new Date(),
    duration: "15",
  },
  {
    i: 5,
    name: "Friday",
    value: "fri",
    isSelected: false,
    startTime: new Date(),
    endTime: new Date(),
    duration: "15",
  },
  {
    i: 6,
    name: "Saturday",
    value: "sat",
    isSelected: false,
    startTime: new Date(),
    endTime: new Date(),
    duration: "15",
  },
];

export const ServiceList = [
  { id: 1, name: "Consultation (Virtual)", value: "Consultation (Virtual)" },
  { id: 2, name: "Consultation (Physical)", value: "Consultation (Physical)" },
  {
    id: 3,
    name: "Consultation (Home Visit)",
    value: "Consultation (Home Visit)",
  },
  { id: 4, name: "Wellness Exams", value: "Wellness Exams" },
  { id: 5, name: "Vaccinations", value: "Vaccinations" },
  { id: 6, name: "Emergency Care", value: "Emergency Care" },
  { id: 7, name: "Surgery", value: "Surgery" },
  { id: 8, name: "Dental Care", value: "Dental Care" },
  { id: 9, name: "Diagnostic Testing", value: "Diagnostic Testing" },
  { id: 10, name: "Behavioral Counseling", value: "Behavioral Counseling" },
  { id: 11, name: "Nutritional Counseling", value: "Nutritional Counseling" },
  { id: 12, name: "Microchipping", value: "Microchipping" },
  { id: 13, name: "Grooming", value: "Grooming" },
  { id: 14, name: "Senior Pet Care", value: "Senior Pet Care" },
  { id: 15, name: "Pet Boarding", value: "Pet Boarding" },
  {
    id: 16,
    name: "Euthanasia and End-of-Life Care",
    value: "Euthanasia and End-of-Life Care",
  },
];

export const roleList = [
  { id: 1, name: "Admin", value: "admin", isSelected: false },
  { id: 2, name: "Billing", value: "billing", isSelected: false },
  { id: 3, name: "Front Desk", value: "frontdesk", isSelected: false },
  { id: 4, name: "Management", value: "management", isSelected: false },
  { id: 5, name: "Pharmacy", value: "pharmacy", isSelected: false },
  { id: 6, name: "Veterinarian", value: "veterinarian", isSelected: false },
];
export const newRoleList = [
  {
    id: 1,
    name: "Junior Veterinarian",
    value: "Junior Veterinarian",
    isSelected: false,
  },
  {
    id: 2,
    name: "Senior Veterinarian",
    value: "Senior Veterinarian",
    isSelected: false,
  },
  { id: 3, name: "Specialist", value: "Specialist", isSelected: false },
];

export const InventoryList = [
  { id: 1, name: "Patient Sale", value: "Patient Sale", isSelected: false },
  { id: 2, name: "Adjustment Add", value: "Adjustment Add", isSelected: false },
  {
    id: 3,
    name: "Adjustment Minus",
    value: "Adjustment Minus",
    isSelected: false,
  },
  { id: 4, name: "Internal Use", value: "Internal Use", isSelected: false },
  { id: 5, name: "Stock Entry", value: "Stock Entry", isSelected: false },
];

export const NewRefundList = [
  { id: 1, name: "Yes", value: "Y" },
  { id: 2, name: "No", value: "N" },
];

export const PrepaidPostpaidList = [
  { id: 1, name: "Prepaid", value: "prepaid" },
  { id: 2, name: "Postpaid", value: "postpaid" },
];

export const PercentageZeroList = [{ id: 1, name: "0", value: "0" }];

export const Percentage50and100List = [
  { id: 1, name: "50", value: "50" },
  { id: 2, name: "100", value: "100" },
];

export const ConsultationList = [
  { id: 1, name: "Virtual", value: "Virtual", isSelected: false },
  { id: 2, name: "Physical", value: "Physical", isSelected: false },
  { id: 3, name: "HomeVisit", value: "HomeVisit", isSelected: false },
];

export const CategoryList = [
  { id: 1, name: "Medication", value: "Medication" },
  { id: 2, name: "Vaccination", value: "Vaccination" },
  { id: 3, name: "Deworming", value: "Deworming" },
];

export const unitTypeList = [
  { id: 1, name: "Box", value: "Box", isSelected: false },
  { id: 2, name: "Bottle", value: "Bottle", isSelected: false },
  { id: 3, name: "Ointment", value: "Ointment", isSelected: false },
  { id: 4, name: "Pack", value: "Pack", isSelected: false },
  { id: 5, name: "Piece", value: "Piece", isSelected: false },
  { id: 6, name: "Strip", value: "Strip", isSelected: false },
  { id: 7, name: "Tablet", value: "Tablet", isSelected: false },
];

export const stockTransition = [
  { id: 1, name: "Stock Entry", value: "Stock Entry", isSelected: false },
  {
    id: 2,
    name: "Stock transcation",
    value: "Stock transcation",
    isSelected: false,
  },
];

export const issueList = [
  { id: 1, name: "Ears", value: "Ears" },
  { id: 2, name: "Eye", value: "Eyes" },
  { id: 3, name: "Mouth", value: "Mouth" },
  { id: 4, name: "Gastrointestinal", value: "Gastrointestinal" },
  { id: 5, name: "Limping", value: "Limping" },
  { id: 6, name: "Breathing", value: "Breathing" },
  { id: 7, name: "Skin", value: "Skin" },
  { id: 8, name: "Urine", value: "Urine" },
  { id: 9, name: "Emergency", value: "Emergency" },
  { id: 10, name: "General", value: "General" },
];

export const VaccineNames = [
  { id: 1, name: "Nobivac® Puppy DPV", value: "Nobivac® Puppy DPV" },
  { id: 2, name: "Vanguard Plus 5", value: "Vanguard Plus 5" },
  { id: 3, name: "Nobivac® Canine 1-Cv", value: "Nobivac® Canine 1-Cv" },
  { id: 4, name: "Duramune Max 5", value: "Duramune Max 5" },
  { id: 5, name: "Nobivac® Canine 1-Cv", value: "Nobivac® Canine 1-Cv" },
  { id: 6, name: "Vanguard Plus 5", value: "Vanguard Plus 5" },
  { id: 7, name: "Nobivac® Rabies", value: "Nobivac® Rabies" },
  { id: 8, name: "Rabvac 3", value: "Rabvac 3" },
  { id: 9, name: "Nobivac® Lepto4", value: "Nobivac® Lepto4" },
  { id: 10, name: "Vanguard L4", value: "Vanguard L4" },
  { id: 11, name: "Bronchi-Shield III", value: "Bronchi-Shield III" },
  { id: 12, name: "Nobivac® Intra-Trac3", value: "Nobivac® Intra-Trac3" },
  { id: 13, name: "Nobivac® PI", value: "Nobivac® PI" },
  { id: 14, name: "Nobivac® Lyme", value: "Nobivac® Lyme" },
  { id: 15, name: "Recombitek® Lyme", value: "Recombitek® Lyme" },
  { id: 16, name: "CaniLeish", value: "CaniLeish" },
  { id: 17, name: "Letifend", value: "Letifend" },
  { id: 18, name: "Babesia", value: "Babesia" },
  {
    id: 19,
    name: "Nobivac® Canine Flu H3N8",
    value: "Nobivac® Canine Flu H3N8",
  },
  { id: 20, name: "Canine Flu H3N2 Vaccine", value: "Canine Flu H3N2 Vaccine" },
  {
    id: 21,
    name: "NOBIVAC® CANINE FLU BIVALENT",
    value: "NOBIVAC® CANINE FLU BIVALENT",
  },
  { id: 22, name: "Vanguard® Civ H3n2", value: "Vanguard® Civ H3n2" },
  { id: 23, name: "Nobivac® Feline 1-HCPCh", value: "Nobivac® Feline 1-HCPCh" },
  { id: 24, name: "Fel-O-Vax PCT", value: "Fel-O-Vax PCT" },
  { id: 24, name: "Nobivac® Feline 1-HCPCh", value: "Nobivac® Feline 1-HCPCh" },
  { id: 25, name: "Fel-O-Vax PCT", value: "Fel-O-Vax PCT" },
  { id: 26, name: "Nobivac® FeLV", value: "Nobivac® FeLV" },
  { id: 27, name: "PUREVAX® FeLV", value: "PUREVAX® FeLV" },
  { id: 28, name: "Fel-O-Vax FIV", value: "Fel-O-Vax FIV" },
  { id: 29, name: "Nobivac® Feline 1-HCPCh", value: "Nobivac® Feline 1-HCPCh" },
  {
    id: 30,
    name: "Bordetella bronchiseptica",
    value: "Bordetella bronchiseptica",
  },

  { id: 31, name: "Clostridial vaccines", value: "Clostridial vaccines" },
  {
    id: 32,
    name: "Bovine Respiratory Syncytial Virus (BRSV) vaccine",
    value: "Bovine Respiratory Syncytial Virus (BRSV) vaccine",
  },
  {
    id: 33,
    name: "Infectious Bovine Rhinotracheitis (IBR) vaccine",
    value: "Infectious Bovine Rhinotracheitis (IBR) vaccine",
  },
  {
    id: 34,
    name: "Parainfluenza-3 (PI3) vaccine",
    value: "Parainfluenza-3 (PI3) vaccine",
  },
  {
    id: 35,
    name: "Bovine Viral Diarrhea (BVD) vaccine",
    value: "Bovine Viral Diarrhea (BVD) vaccine",
  },
  { id: 36, name: "Leptospirosis vaccine", value: "Leptospirosis vaccine" },
  {
    id: 37,
    name: "Foot and Mouth Disease (FMD) vaccine",
    value: "Foot and Mouth Disease (FMD) vaccine",
  },
  {
    id: 38,
    name: "Eastern/Western Equine Encephalomyelitis (EEE/WEE) vaccine",
    value: "Eastern/Western Equine Encephalomyelitis (EEE/WEE) vaccine",
  },
  { id: 39, name: "Tetanus Toxoid", value: "Tetanus Toxoid" },
  {
    id: 40,
    name: "West Nile Virus (WNV) vaccine",
    value: "West Nile Virus (WNV) vaccine",
  },
  { id: 41, name: "Rabies vaccine", value: "Rabies vaccine" },
  {
    id: 42,
    name: "Rhino pneumonitis vaccines (Equine Herpes Virus types 1 and 4)",
    value: "Rhino pneumonitis vaccines (Equine Herpes Virus types 1 and 4)",
  },
  {
    id: 43,
    name: "Clostridial vaccines (CD&T for Tetanus and Clostridium perfringens types C and D)",
    value:
      "Clostridial vaccines (CD&T for Tetanus and Clostridium perfringens types C and D)",
  },
  {
    id: 44,
    name: "Porcine Circovirus Type 2 (PCV2) vaccine",
    value: "Porcine Circovirus Type 2 (PCV2) vaccine",
  },
  {
    id: 45,
    name: "Porcine Circovirus Type 2 (PCV2) vaccine",
    value: "Porcine Circovirus Type 2 (PCV2) vaccine",
  },
  {
    id: 46,
    name: "Swine Influenza Virus (SIV) vaccine",
    value: "Swine Influenza Virus (SIV) vaccine",
  },
  { id: 47, name: "Erysipelas vaccine", value: "Erysipelas vaccine" },
  {
    id: 48,
    name: "Porcine Reproductive and Respiratory Syndrome (PRRS) vaccine",
    value: "Porcine Reproductive and Respiratory Syndrome (PRRS) vaccine",
  },
];

export const FleaBiteList = [
  { id: 1, name: "Capstar", value: "Capstar" },
  { id: 2, name: "Comfortis, Trifexis", value: "Comfortis, Trifexis" },
  { id: 2, name: "NexGard", value: "NexGard" },
  {
    id: 4,
    name: "Bravecto (Chewable and Topical)",
    value: "Bravecto (Chewable and Topical)",
  },
  { id: 5, name: "Credelio", value: "Credelio" },
  {
    id: 6,
    name: "Simparica, Simparica Trio",
    value: "Simparica, Simparica Trio",
  },
  {
    id: 7,
    name: "Frontline, Frontline Spray",
    value: "Frontline, Frontline Spray",
  },
  { id: 8, name: "Revolution, Stronghold", value: "Revolution, Stronghold" },
  { id: 9, name: "Vectra", value: "Vectra" },
  { id: 10, name: "Scalibor Protector Band", value: "Scalibor Protector Band" },
  { id: 11, name: "Seresto", value: "Seresto" },
  { id: 12, name: "Various brands", value: "Various brands" },
  {
    id: 13,
    name: "Advocate, Advantage Multi",
    value: "Advocate, Advantage Multi",
  },
  { id: 14, name: "Sentinel", value: "Sentinel" },
];

export const DewormingList = [
  {
    id: 1,
    name: "Nemex, Strongid T, Drontal",
    value: "Nemex, Strongid T, Drontal",
  },
  { id: 2, name: "Panacur, Safe-Guard", value: "Panacur, Safe-Guard" },
  {
    id: 3,
    name: "Droncit, Drontal, Profender",
    value: "Droncit, Drontal, Profender",
  },
  {
    id: 4,
    name: "Interceptor, Sentinel, Trifexis",
    value: "Interceptor, Sentinel, Trifexis",
  },
  {
    id: 5,
    name: "Quest, Advantage Multi, ProHeart",
    value: "Quest, Advantage Multi, ProHeart",
  },
  { id: 6, name: "Drontal, Panacur", value: "Drontal, Panacur" },
  { id: 7, name: "Drontal Plus", value: "Drontal Plus" },
  { id: 8, name: "Filaribits", value: "Filaribits" },
  { id: 9, name: "Valbazen", value: "Valbazen" },
  {
    id: 10,
    name: "Heartgard, Ivomec, Iverhart",
    value: "Heartgard, Ivomec, Iverhart",
  },
  { id: 11, name: "Tramisol, Levasole", value: "Tramisol, Levasole" },
  { id: 12, name: "Profender", value: "Profender" },
  { id: 13, name: "Dectomax", value: "Dectomax" },
  { id: 14, name: "Revolution, Stronghold", value: "Revolution, Stronghold" },
];

export const MedicationList = [
  { id: 1, name: "Precose", value: "Precose" },
  { id: 2, name: "Carrisyn™", value: "Carrisyn™" },
  { id: 3, name: "PromAce® Injectable", value: "PromAce® Injectable" },
  { id: 4, name: "PromAce®", value: "PromAce®" },
  {
    id: 5,
    name: "Acepromazine Maleate Injection",
    value: "Acepromazine Maleate Injection",
  },
  {
    id: 6,
    name: "Acepromazine Maleate Tablets",
    value: "Acepromazine Maleate Tablets",
  },
  { id: 7, name: "Tylenol", value: "Tylenol" },
  { id: 8, name: "Diamox", value: "Diamox" },
  { id: 9, name: "Acetic Acid", value: "Acetic Acid" },
  { id: 10, name: "Acetohydroxamic Acid", value: "Acetohydroxamic Acid" },
  { id: 11, name: "Mucomyst", value: "Mucomyst" },
  { id: 12, name: "Soriatane", value: "Soriatane" },
  { id: 13, name: "Zovirax", value: "Zovirax" },
  { id: 14, name: "Aglepristone", value: "Aglepristone" },
  { id: 15, name: "Valbazen", value: "Valbazen" },
  { id: 16, name: "canine albumin", value: "canine albumin" },
  { id: 17, name: "Ventolin", value: "Ventolin" },
  { id: 18, name: "Fosamax", value: "Fosamax" },
  { id: 19, name: "Alfaxan® Multidose", value: "Alfaxan® Multidose" },
  { id: 20, name: "Allopurinol", value: "Allopurinol" },
  { id: 21, name: "Alprazolam", value: "Alprazolam" },
  { id: 22, name: "Regu-Mate®", value: "Regu-Mate®" },
  { id: 23, name: "Matrix®", value: "Matrix®" },
  { id: 24, name: "OvaMed®", value: "OvaMed®" },
  { id: 25, name: "ChronoMate™", value: "ChronoMate™" },
  { id: 26, name: "Altren®", value: "Altren®" },
  { id: 27, name: "SwineMate®", value: "SwineMate®" },
  { id: 28, name: "Aluminum Hydroxide", value: "Aluminum Hydroxide" },
  { id: 29, name: "Amantadine HCl", value: "Amantadine HCl" },
  { id: 30, name: "AmiMax™ E Solution", value: "AmiMax™ E Solution" },
  {
    id: 31,
    name: "Amikacin Sulfate Injection",
    value: "Amikacin Sulfate Injection",
  },
  { id: 32, name: "Aminocaproic Acid", value: "Aminocaproic Acid" },
  { id: 33, name: "Centrine Oral Tablets", value: "Centrine Oral Tablets" },
  { id: 34, name: "Centrine Injectable", value: "Centrine Injectable" },
  { id: 35, name: "Aminophylline", value: "Aminophylline" },
  { id: 36, name: "Amiodarone HCl", value: "Amiodarone HCl" },
  { id: 37, name: "Amitriptyline HCl", value: "Amitriptyline HCl" },
  { id: 38, name: "Amlodipine Besylate", value: "Amlodipine Besylate" },
  { id: 39, name: "Ammonium Chloride", value: "Ammonium Chloride" },
  { id: 40, name: "Ammonium Molybdate", value: "Ammonium Molybdate" },
  {
    id: 41,
    name: "Ammonium Tetrathiomolybdate",
    value: "Ammonium Tetrathiomolybdate",
  },
  { id: 42, name: "Amoxil", value: "Amoxil" },
  { id: 43, name: "Augmentin", value: "Augmentin" },
  {
    id: 44,
    name: "Amphotericin B Desoxycholate",
    value: "Amphotericin B Desoxycholate",
  },
  { id: 45, name: "Abelcet (typical brand)", value: "Abelcet (typical brand)" },
  { id: 46, name: "Ampicillin", value: "Ampicillin" },
  {
    id: 47,
    name: "Unasyn (human equivalent)",
    value: "Unasyn (human equivalent)",
  },
  { id: 48, name: "Corid", value: "Corid" },
  {
    id: 49,
    name: "Antivenin (Crotalidae) Polyvalent",
    value: "Antivenin (Crotalidae) Polyvalent",
  },
  { id: 50, name: "CroFab", value: "CroFab" },
  {
    id: 51,
    name: "Antivenin Latrodectus Mactans",
    value: "Antivenin Latrodectus Mactans",
  },
  {
    id: 52,
    name: "Antivenin Micrurus Fulvius",
    value: "Antivenin Micrurus Fulvius",
  },
  { id: 53, name: "Apomorphine", value: "Apomorphine" },
  { id: 54, name: "Apralan™ 75", value: "Apralan™ 75" },
  { id: 55, name: "Ascorbic Acid", value: "Ascorbic Acid" },
  { id: 56, name: "Elspar", value: "Elspar" },
  { id: 57, name: "Aspirin", value: "Aspirin" },
  { id: 58, name: "Atenolol", value: "Atenolol" },
  { id: 59, name: "Antisedan", value: "Antisedan" },
  { id: 60, name: "Atovaquone", value: "Atovaquone" },
  { id: 61, name: "Atracurium Besylate", value: "Atracurium Besylate" },
  { id: 62, name: "Atropine Sulfate", value: "Atropine Sulfate" },
  { id: 63, name: "Ridaura", value: "Ridaura" },
  { id: 64, name: "Auranofin", value: "Auranofin" },
  { id: 65, name: "Stresnil Injection", value: "Stresnil Injection" },
  { id: 66, name: "Azathioprine", value: "Azathioprine" },
  { id: 67, name: "Azithromycin", value: "Azithromycin" },
  { id: 68, name: "Mitaban", value: "Mitaban" },
  { id: 69, name: "Taktic", value: "Taktic" },
  { id: 70, name: "Preventic", value: "Preventic" },
  { id: 71, name: "Azactam", value: "Azactam" },
  { id: 72, name: "Baclofen", value: "Baclofen" },
  { id: 73, name: "Phenobarbital", value: "Phenobarbital" },
  { id: 74, name: "Lotensin", value: "Lotensin" },
  { id: 75, name: "Celestone", value: "Celestone" },
  { id: 76, name: "Urecholine", value: "Urecholine" },
  { id: 77, name: "Dulcolax", value: "Dulcolax" },
  { id: 78, name: "Pepto-Bismol", value: "Pepto-Bismol" },
  { id: 79, name: "Bleomycin Sulfate", value: "Bleomycin Sulfate" },
  { id: 80, name: "Equipoise", value: "Equipoise" },
  { id: 81, name: "Bromide", value: "Bromide" },
  { id: 82, name: "Parlodel", value: "Parlodel" },
  { id: 83, name: "Entocort", value: "Entocort" },
  { id: 84, name: "Buprenex", value: "Buprenex" },
  { id: 85, name: "Buspar", value: "Buspar" },
  { id: 86, name: "Busulfan", value: "Busulfan" },
  { id: 87, name: "(Specific brand needed)", value: "(Specific brand needed)" },
  {
    id: 88,
    name: "Butorphanol Tartrate Injection",
    value: "Butorphanol Tartrate Injection",
  },
  { id: 89, name: "Butorphic™ Injection", value: "Butorphic™ Injection" },
  { id: 90, name: "Torphadine", value: "Torphadine" },
  { id: 91, name: "Dolorex", value: "Dolorex" },
  { id: 92, name: "Torbugesic-SA® Vet", value: "Torbugesic-SA® Vet" },
  { id: 93, name: "Torbugesic®", value: "Torbugesic®" },
  { id: 94, name: "Torbutrol® Tablets", value: "Torbutrol® Tablets" },
  { id: 95, name: "Torbutrol® Injection", value: "Torbutrol® Injection" },
  { id: 96, name: "Cabergoline", value: "Cabergoline" },
  { id: 97, name: "Miacalcin", value: "Miacalcin" },
  { id: 98, name: "Calcitriol", value: "Calcitriol" },
  { id: 99, name: "Calcium Acetate", value: "Calcium Acetate" },
  { id: 100, name: "Calcium Salts", value: "Calcium Salts" },
  { id: 101, name: "calcium carbonate", value: "calcium carbonate" },
  { id: 102, name: "calcium citrate", value: "calcium citrate" },
  { id: 103, name: "Captopril", value: "Captopril" },
  { id: 104, name: "Carbamazepine", value: "Carbamazepine" },
  { id: 105, name: "Clarithromycin", value: "Clarithromycin" },
  { id: 106, name: "Tegretol", value: "Tegretol" },
  { id: 107, name: "Carbimazole", value: "Carbimazole" },
  { id: 108, name: "Carboplatin", value: "Carboplatin" },
  { id: 109, name: "L-Carnitine", value: "L-Carnitine" },
  { id: 110, name: "Carprofen Tablets", value: "Carprofen Tablets" },
  { id: 111, name: "Carofenvet™", value: "Carofenvet™" },
  { id: 112, name: "Carprofen", value: "Carprofen" },
  {
    id: 113,
    name: "CARPROFEN Chewable Tablets",
    value: "CARPROFEN Chewable Tablets",
  },
  { id: 114, name: "Carprieve® Chewable Tablets", value: "Coban" },
  { id: 115, name: "Carprofen Injection", value: "Carprofen Injection" },
  {
    id: 116,
    name: "Carprofen Flavored Tablets",
    value: "Carprofen Flavored Tablets",
  },
  {
    id: 117,
    name: "Carprofen Sterile Injectable Solution",
    value: "Carprofen Sterile Injectable Solution",
  },
  { id: 118, name: "quellin®", value: "quellin®" },
  {
    id: 119,
    name: "Rimadyl® Chewable Tablets",
    value: "Rimadyl® Chewable Tablets",
  },
  {
    id: 120,
    name: "Rimadyl® Sterile Injectable Solution",
    value: "Rimadyl® Sterile Injectable Solution",
  },
  {
    id: 121,
    name: "Carprofen Caplets, Novox® Caplets",
    value: "Carprofen Caplets, Novox® Caplets",
  },
  { id: 122, name: "Rimadyl® Caplets", value: "Rimadyl® Caplets" },
  { id: 123, name: "CARPRIEVE®", value: "CARPRIEVE®" },
  { id: 124, name: "Carprieve® Injection", value: "Carprieve® Injection" },
  { id: 125, name: "Vetprofen™", value: "Vetprofen™" },
  { id: 126, name: "Carvedilol", value: "Carvedilol" },
  { id: 127, name: "Cancidas", value: "Cancidas" },
  { id: 128, name: "Cefaclor", value: "Cefaclor" },
  { id: 129, name: "Cefa-Tabs®", value: "Cefa-Tabs®" },
  { id: 130, name: "Cefa-Drops®", value: "Cefa-Drops®" },
  { id: 131, name: "Cefazolin Sodium", value: "Cefazolin Sodium" },
  { id: 132, name: "Cefepime HCl", value: "Cefepime HCl" },
  { id: 133, name: "Cefixime", value: "Cefixime" },
  { id: 134, name: "Cefotaxime Sodium", value: "Cefotaxime Sodium" },
  { id: 135, name: "Cefotetan Disodium", value: "Cefotetan Disodium" },
  { id: 136, name: "Cefovecin Sodium", value: "Cefovecin Sodium" },
  { id: 137, name: "Cefoxitin Sodium", value: "Cefoxitin Sodium" },
  { id: 138, name: "Cefpodoxime Proxetil", value: "Cefpodoxime Proxetil" },
  { id: 139, name: "Ceftazidime", value: "Ceftazidime" },
  { id: 140, name: "Ceftibuten", value: "Ceftibuten" },
  { id: 141, name: "Ceftiofur", value: "Ceftiofur" },
  { id: 142, name: "EXCEDE®", value: "EXCEDE®" },
  { id: 143, name: "EXCEDE® FOR SWINE", value: "EXCEDE® FOR SWINE" },
  { id: 144, name: "Excenel® RTU EZ", value: "Excenel® RTU EZ" },
  { id: 145, name: "Ceftriaxone", value: "Ceftriaxone" },
  { id: 146, name: "Zinacef", value: "Zinacef" },
  { id: 147, name: "Celebrex", value: "Celebrex" },
  { id: 148, name: "Rilexine®", value: "Rilexine®" },
  { id: 149, name: "Cephalothin", value: "Cephalothin" },
  { id: 150, name: "Cephapirin", value: "Cephapirin" },
  { id: 151, name: "Ceritinib", value: "Ceritinib" },
  { id: 152, name: "Cetirizine", value: "Cetirizine" },
  { id: 153, name: "Chloral Hydrate", value: "Chloral Hydrate" },
  { id: 154, name: "Leukeran", value: "Leukeran" },
  { id: 155, name: "Medichol Tablets", value: "Medichol Tablets" },
  { id: 156, name: "Mychel-Vet Tabs", value: "Mychel-Vet Tabs" },
  { id: 157, name: "Mychel-Vet Injection", value: "Mychel-Vet Injection" },
  { id: 158, name: "Anacetin Tablets", value: "Flumazenil for Injection" },
  {
    id: 159,
    name: "Chloramphenicol 1% Ophthalmic, Vetrocloricin Ophthalmic Ointment",
    value: "Fluorouracil Injection",
  },
  {
    id: 160,
    name: "Mychel-Vet Capsules (50 mg)",
    value: "Furosemide Injection",
  },
  {
    id: 161,
    name: "Chloramphenicol Capsules",
    value: "Chloramphenicol Capsules",
  },
  {
    id: 162,
    name: "Chloromycetin Ophthalmic Ointment",
    value: "Chloromycetin Ophthalmic Ointment",
  },
  { id: 163, name: "Viceton® Tablets", value: "Viceton® Tablets" },
  {
    id: 164,
    name: "Chloromycetin Tablets 100 mg",
    value: "Chloromycetin Tablets 100 mg",
  },
  {
    id: 165,
    name: "Chloromycetin Tablets 250 mg",
    value: "Chloromycetin Tablets 250 mg",
  },
  {
    id: 166,
    name: "Chloromycetin Tablets 500 mg",
    value: "Chloromycetin Tablets 500 mg",
  },
  { id: 167, name: "Tevcocin", value: "Tevcocin" },
  { id: 168, name: "Chlorhexidine", value: "Chlorhexidine" },
  { id: 169, name: "Chlorothiazide", value: "Chlorothiazide" },
  { id: 170, name: "Chlorpheniramine", value: "Chlorpheniramine" },
  { id: 171, name: "Chlorpromazine", value: "Chlorpromazine" },
  { id: 172, name: "Chlorpropamide", value: "Chlorpropamide" },
  { id: 173, name: "Deracin™ 50 Meal", value: "Deracin™ 50 Meal" },
  { id: 174, name: "Deracin™ 90 Meal", value: "Deracin™ 90 Meal" },
  { id: 175, name: "Deracin™ 100 Meal", value: "Deracin™ 100 Meal" },
  { id: 176, name: "Pennchlor® 50™", value: "Pennchlor® 50™" },
  { id: 177, name: "Pennchlor 50 G®", value: "Pennchlor 50 G®" },
  { id: 178, name: "Pennchlor® 90 G™", value: "Pennchlor® 90 G™" },
  { id: 179, name: "Pennchlor® 100 G™", value: "Pennchlor® 100 G™" },
  { id: 180, name: "Pennchlor® 100 Hi-Flo™", value: "Pennchlor® 100 Hi-Flo™" },
  {
    id: 181,
    name: "Aureomycin® 50 Granular",
    value: "Aureomycin® 50 Granular",
  },
  {
    id: 182,
    name: "Aureomycin® 50 Granular A",
    value: "Aureomycin® 50 Granular A",
  },
  {
    id: 183,
    name: "Aureomycin® 70 Granular",
    value: "Aureomycin® 70 Granular",
  },
  {
    id: 184,
    name: "Aureomycin® 80 Granular",
    value: "Aureomycin® 80 Granular",
  },
  {
    id: 185,
    name: "Aureomycin® 90 Granular",
    value: "Aureomycin® 90 Granular",
  },
  { id: 186, name: "Aureomycin® 90 Meal", value: "Aureomycin® 90 Meal" },
  {
    id: 187,
    name: "Aureomycin® 100 Granular",
    value: "Aureomycin® 100 Granular",
  },
  { id: 188, name: "PfiChlor® 100S", value: "PfiChlor® 100S" },
  { id: 189, name: "Cholestyramine", value: "Cholestyramine" },
  { id: 190, name: "Choline Salicylate", value: "Choline Salicylate" },
  { id: 191, name: "Cidofovir", value: "Cidofovir" },
  { id: 192, name: "Tagamet", value: "Tagamet" },
  { id: 193, name: "Ciprofloxacin", value: "Ciprofloxacin" },
  { id: 194, name: "Cipro", value: "Cipro" },
  { id: 195, name: "Cisapride", value: "Cisapride" },
  { id: 196, name: "Cisplatin", value: "Cisplatin" },
  { id: 197, name: "Biaxin", value: "Biaxin" },
  { id: 198, name: "Clemastine", value: "Clemastine" },
  { id: 199, name: "ClindaMed™ Oral Drops", value: "ClindaMed™ Oral Drops" },
  { id: 200, name: "Antirobe", value: "Antirobe" },
  { id: 201, name: "Clioquinol", value: "Clioquinol" },
  { id: 202, name: "Clomicalm", value: "Clomicalm" },
  { id: 203, name: "Clonazepam", value: "Clonazepam" },
  { id: 204, name: "Clonidine", value: "Clonidine" },
  { id: 205, name: "Clopidogrel", value: "Clopidogrel" },
  { id: 206, name: "Plavix", value: "Plavix" },
  { id: 207, name: "Clorazepate", value: "Clorazepate" },
  { id: 208, name: "Tranxene", value: "Tranxene" },
  {
    id: 209,
    name: "Veltrim 1% Dermatologic Cream",
    value: "Veltrim 1% Dermatologic Cream",
  },
  { id: 210, name: "Cloxacillin", value: "Cloxacillin" },
  { id: 211, name: "Codeine", value: "Codeine" },
  { id: 212, name: "Colchicine", value: "Colchicine" },
  { id: 213, name: "Colesevelam", value: "Colesevelam" },
  { id: 214, name: "Welchol", value: "Welchol" },
  { id: 215, name: "Colestipol", value: "Colestipol" },
  { id: 216, name: "Colestid", value: "Colestid" },
  { id: 217, name: "Santyl", value: "Santyl" },
  { id: 218, name: "Collagenase", value: "Collagenase" },
  { id: 219, name: "Adrenomone", value: "Adrenomone" },
  { id: 220, name: "ACTH Gel", value: "ACTH Gel" },
  { id: 221, name: "Acthar", value: "Acthar" },
  { id: 222, name: "Cortisone", value: "Cortisone" },
  { id: 223, name: "Cortone Acetate", value: "Cortone Acetate" },
  { id: 224, name: "Cromolyn", value: "Cromolyn" },
  { id: 225, name: "Crolom", value: "Crolom" },
  { id: 226, name: "Cyclobenzaprine", value: "Cyclobenzaprine" },
  { id: 227, name: "Flexeril", value: "Flexeril" },
  { id: 228, name: "Cyclophosphamide", value: "Cyclophosphamide" },
  { id: 229, name: "Cytoxan", value: "Cytoxan" },
  { id: 230, name: "MODULIS® for Dogs", value: "MODULIS® for Dogs" },
  { id: 231, name: "Cyclavance®", value: "Cyclavance®" },
  { id: 232, name: "Sporimune™", value: "Sporimune™" },
  { id: 233, name: "Atopica™", value: "Atopica™" },
  { id: 234, name: "Optimmune®", value: "Optimmune®" },
  { id: 235, name: "Neoral", value: "Neoral" },
  { id: 236, name: "Cyproheptadine", value: "Cyproheptadine" },
  {
    id: 237,
    name: "Proban® Cythioate Tablets 30 mg",
    value: "Proban® Cythioate Tablets 30 mg",
  },
  { id: 238, name: "Proban® Oral Liquid", value: "Proban® Oral Liquid" },
  { id: 239, name: "Proban® Tablets", value: "Proban® Tablets" },
  { id: 240, name: "Dacarbazine", value: "Dacarbazine" },
  { id: 241, name: "Danazol", value: "Danazol" },
  { id: 242, name: "Dantrolene", value: "Dantrolene" },
  { id: 243, name: "Dapsone", value: "Dapsone" },
  { id: 244, name: "Darbepoetin Alfa", value: "Darbepoetin Alfa" },
  { id: 245, name: "Aranesp®", value: "Aranesp®" },
  { id: 246, name: "Desipramine", value: "Desipramine" },
  { id: 247, name: "Desmopressin", value: "Desmopressin" },
  { id: 248, name: "DDAVP", value: "DDAVP" },
  {
    id: 249,
    name: "Dexamethasone Injection",
    value: "Dexamethasone Injection",
  },
  { id: 250, name: "Dexium®", value: "Dexium®" },
  { id: 251, name: "Dexachel", value: "Dexachel" },
  { id: 252, name: "Zonometh Solution", value: "Zonometh Solution" },
  {
    id: 253,
    name: "Dexamethasone Sterile Solution",
    value: "Dexamethasone Sterile Solution",
  },
  { id: 254, name: "Pet Derm® III Tablets", value: "Pet Derm® III Tablets" },
  { id: 255, name: "Dexameth-A-Vet", value: "Dexameth-A-Vet" },
  { id: 256, name: "Dexamethasone Solution", value: "Dexamethasone Solution" },
  { id: 257, name: "Dexium™ Tablets", value: "Dexium™ Tablets" },
  {
    id: 258,
    name: "Azium® Oral Solution 2 mg",
    value: "Azium® Oral Solution 2 mg",
  },
  { id: 259, name: "Azium® Boluses 10 mg", value: "Azium® Boluses 10 mg" },
  { id: 260, name: "Azium® Powder", value: "Azium® Powder" },
  { id: 261, name: "Azium® Solution", value: "Azium® Solution" },
  {
    id: 262,
    name: "Dexameth-A-Vet Injection",
    value: "Dexameth-A-Vet Injection",
  },
  {
    id: 263,
    name: "Azium® Aqueous Suspension Veterinary",
    value: "Azium® Aqueous Suspension Veterinary",
  },
  { id: 264, name: "Azium® Tablets 0.25 mg", value: "Azium® Tablets 0.25 mg" },
  { id: 265, name: "SILEO®", value: "SILEO®" },
  { id: 266, name: "Diazepam", value: "Diazepam" },
  { id: 267, name: "Valium", value: "Valium" },
  { id: 268, name: "Diastat", value: "Diastat" },
  { id: 269, name: "Diazemuls", value: "Diazemuls" },
  { id: 270, name: "Diazoxide", value: "Diazoxide" },
  { id: 271, name: "Diclofenac", value: "Diclofenac" },
  { id: 272, name: "Dicloxacillin", value: "Dicloxacillin" },
  { id: 273, name: "Dicyclomine", value: "Dicyclomine" },
  { id: 274, name: "Bentyl", value: "Bentyl" },
  { id: 275, name: "Diethylcarbamazine", value: "Diethylcarbamazine" },
  { id: 276, name: "Hetrazan", value: "Hetrazan" },
  { id: 277, name: "Difloxacin", value: "Difloxacin" },
  { id: 278, name: "Lanoxin", value: "Lanoxin" },
  { id: 279, name: "Digoxin", value: "Digoxin" },
  { id: 280, name: "Dihydroergotamine", value: "Dihydroergotamine" },
  { id: 281, name: "D.H.E. 45", value: "D.H.E. 45" },
  { id: 282, name: "Diltiazem", value: "Diltiazem" },
  { id: 283, name: "Cardizem", value: "Cardizem" },
  { id: 284, name: "Dramamine", value: "Dramamine" },
  { id: 285, name: "Benadryl", value: "Benadryl" },
  { id: 286, name: "Lomotil", value: "Lomotil" },
  { id: 287, name: "Diphenoxylate", value: "Diphenoxylate" },
  { id: 288, name: "Zimeta®", value: "Zimeta®" },
  { id: 289, name: "Disopyramide", value: "Disopyramide" },
  { id: 290, name: "Norpace", value: "Norpace" },
  { id: 291, name: "Dobutamine", value: "Dobutamine" },
  { id: 292, name: "Dobutrex", value: "Dobutrex" },
  { id: 293, name: "Taxotere", value: "Taxotere" },
  { id: 294, name: "Motilium", value: "Motilium" },
  { id: 295, name: "Domperidone", value: "Domperidone" },
  { id: 296, name: "Aricept", value: "Aricept" },
  { id: 297, name: "Dopamine", value: "Dopamine" },
  {
    id: 298,
    name: "Dectomax® Injectable Solution for Cattle and Swine",
    value: "Dectomax® Injectable Solution for Cattle and Swine",
  },
  {
    id: 299,
    name: "Dectomax® Pour-on Solution for Cattle",
    value: "Dectomax® Pour-on Solution for Cattle",
  },
  { id: 300, name: "DectoGard™", value: "DectoGard™" },
  { id: 301, name: "Doraject™", value: "Doraject™" },
  { id: 302, name: "Dorzolamide", value: "Dorzolamide" },
  { id: 303, name: "Trusopt", value: "Trusopt" },
  { id: 304, name: "Doxapram", value: "Doxapram" },
  { id: 305, name: "Dopram", value: "Dopram" },
  { id: 306, name: "Cardura", value: "Cardura" },
  { id: 307, name: "Doxepin", value: "Doxepin" },
  { id: 308, name: "Sinequan", value: "Sinequan" },
  { id: 309, name: "Doxorubicin", value: "Doxorubicin" },
  { id: 310, name: "Adriamycin", value: "Adriamycin" },
  { id: 311, name: "Doxycycline", value: "Doxycycline" },
  { id: 312, name: "Multaq", value: "Multaq" },
  { id: 313, name: "Cymbalta", value: "Cymbalta" },
  { id: 314, name: "Duramorph", value: "Duramorph" },
  { id: 315, name: "Dydrogesterone", value: "Dydrogesterone" },
  { id: 316, name: "Enalapril", value: "Enalapril" },
  { id: 317, name: "Enflurane", value: "Enflurane" },
  { id: 318, name: "EnroPro™ 100", value: "EnroPro™ 100" },
  { id: 319, name: "EnroPro™ 22.7", value: "EnroPro™ 22.7" },
  { id: 320, name: "Enrofloxacin", value: "Enrofloxacin" },
  {
    id: 321,
    name: "Enroflox® Chewable Tablets",
    value: "Enroflox® Chewable Tablets",
  },
  { id: 322, name: "Tenotryl™", value: "Tenotryl™" },
  {
    id: 323,
    name: "Enrofloxacin Flavored Tablets",
    value: "Enrofloxacin Flavored Tablets",
  },
  { id: 324, name: "ENROFLOXACIN 100", value: "ENROFLOXACIN 100" },
  { id: 325, name: "Zobuxa™", value: "Zobuxa™" },
  { id: 326, name: "EnroMed™ 100", value: "EnroMed™ 100" },
  {
    id: 327,
    name: "Enrofloxacin Antibacterial Injectable Solution",
    value: "Enrofloxacin Antibacterial Injectable Solution",
  },
  {
    id: 328,
    name: "Baytril® Soft Chewable Tablets",
    value: "Baytril® Soft Chewable Tablets",
  },
  {
    id: 329,
    name: "Enroflox™ Injection for Dogs 2.27%",
    value: "Enroflox™ Injection for Dogs 2.27%",
  },
  { id: 330, name: "Enroflox® 100", value: "Enroflox® 100" },
  {
    id: 331,
    name: "Baytril® 100 Injectable Solution",
    value: "Baytril® 100 Injectable Solution",
  },
  {
    id: 332,
    name: "Baytril® Antibacterial Injectable Solution",
    value: "Baytril® Antibacterial Injectable Solution",
  },
  {
    id: 333,
    name: "Baytril® Antibacterial Tablets, Baytril® Taste Tabs® Antibacterial Tablets",
    value:
      "Baytril® Antibacterial Tablets, Baytril® Taste Tabs® Antibacterial Tablets",
  },
  { id: 334, name: "Ephedrine", value: "Ephedrine" },
  { id: 335, name: "Eplerenone", value: "Eplerenone" },
  { id: 336, name: "Epoetin Alfa", value: "Epoetin Alfa" },
  { id: 337, name: "Epoprostenol", value: "Epoprostenol" },
  { id: 338, name: "Eprinex®", value: "Eprinex®" },
  { id: 339, name: "Longrange®", value: "Longrange®" },
  { id: 340, name: "Eprizero®", value: "Eprizero®" },
  { id: 341, name: "EpriGard™", value: "EpriGard™" },
  { id: 342, name: "Ergocalciferol", value: "Ergocalciferol" },
  { id: 343, name: "Ergotamine", value: "Ergotamine" },
  { id: 344, name: "Erythro®-100 Injection", value: "Erythro®-100 Injection" },
  { id: 345, name: "Gallimycin®-36", value: "Gallimycin®-36" },
  { id: 346, name: "Erythromast 36", value: "Erythromast 36" },
  {
    id: 347,
    name: "Gallimycin® Injection, Gallimycin®-100",
    value: "Gallimycin® Injection, Gallimycin®-100",
  },
  {
    id: 348,
    name: "Erythro®-36, Erythro®-Dry",
    value: "Erythro®-36, Erythro®-Dry",
  },
  { id: 349, name: "Esomeprazole", value: "Esomeprazole" },
  { id: 350, name: "Nexium®", value: "Nexium®" },
  { id: 351, name: "Estradiol", value: "Estradiol" },
  { id: 352, name: "Incurin®", value: "Incurin®" },
  { id: 353, name: "Ethacrynic Acid", value: "Ethacrynic Acid" },
  { id: 354, name: "Edecrin®", value: "Edecrin®" },
  { id: 355, name: "Ethanol", value: "Ethanol" },
  { id: 356, name: "Ethosuximide", value: "Ethosuximide" },
  { id: 357, name: "Zarontin®", value: "Zarontin®" },
  {
    id: 358,
    name: "Etogesic® Sterile Injectable Solution",
    value: "Etogesic® Sterile Injectable Solution",
  },
  { id: 359, name: "EtoGesic® Tablets", value: "EtoGesic® Tablets" },
  { id: 360, name: "Etomidate", value: "Etomidate" },
  { id: 361, name: "Etoposide", value: "Etoposide" },
  { id: 362, name: "Vepesid®", value: "Vepesid®" },
  { id: 363, name: "Etoricoxib", value: "Etoricoxib" },
  { id: 364, name: "Arcoxia®", value: "Arcoxia®" },
  { id: 365, name: "Exenatide", value: "Exenatide" },
  { id: 366, name: "Byetta®", value: "Byetta®" },
  { id: 367, name: "Famciclovir", value: "Famciclovir" },
  { id: 368, name: "Famvir®", value: "Famvir®" },
  { id: 369, name: "Famotidine", value: "Famotidine" },
  { id: 370, name: "Pepcid®", value: "Pepcid®" },
  {
    id: 371,
    name: "Rintal® Tabs Anthelmintic Tablets",
    value: "Rintal® Tabs Anthelmintic Tablets",
  },
  {
    id: 372,
    name: "Cutter Paste, Rintal® Paste",
    value: "Cutter Paste, Rintal® Paste",
  },
  { id: 373, name: "Rintal® Suspension", value: "Rintal® Suspension" },
  { id: 374, name: "Safe-Guard® AquaSol", value: "Safe-Guard® AquaSol" },
  { id: 375, name: "Safe-Guard®", value: "Safe-Guard®" },
  {
    id: 376,
    name: "Safe-Guard® Type A Medicated Article",
    value: "Safe-Guard® Type A Medicated Article",
  },
  { id: 377, name: "panacur®, safe-guard®", value: "panacur®, safe-guard®" },
  {
    id: 378,
    name: "Panacur® C (OTC), Safe-Guard® Canine (OTC), Panacur® Granules 22.2% (Rx)",
    value:
      "Panacur® C (OTC), Safe-Guard® Canine (OTC), Panacur® Granules 22.2% (Rx)",
  },
  {
    id: 379,
    name: "Panacur® Granules 22.2%",
    value: "Panacur® Granules 22.2%",
  },
  {
    id: 380,
    name: "Panacur® Suspension 10%",
    value: "Panacur® Suspension 10%",
  },
  { id: 381, name: "Safe-Guard®, Panacur®", value: "Safe-Guard®, Panacur®" },
  { id: 382, name: "Fenbufen", value: "Fenbufen" },
  { id: 383, name: "Fentanyl", value: "Fentanyl" },
  { id: 384, name: "Fexofenadine", value: "Fexofenadine" },
  { id: 385, name: "Filgrastim", value: "Filgrastim" },
  { id: 386, name: "Finasteride", value: "Finasteride" },
  { id: 387, name: "Flavoxate", value: "Flavoxate" },
  { id: 388, name: "Flecainide", value: "Flecainide" },
  { id: 389, name: "Flubendazole", value: "Flubendazole" },
  { id: 390, name: "Fluconazole", value: "Fluconazole" },
  { id: 391, name: "Flucytosine", value: "Flucytosine" },
  { id: 392, name: "Fludrocortisone", value: "Fludrocortisone" },
  { id: 393, name: "Flumazenil", value: "Flumazenil" },
  { id: 394, name: "Banamine® Transdermal", value: "Banamine® Transdermal" },
  { id: 395, name: "Fluocinolone", value: "Fluocinolone" },
  { id: 396, name: "Fluorometholone", value: "Fluorometholone" },
  { id: 397, name: "Fluoxetine", value: "Fluoxetine" },
  { id: 398, name: "Fluphenazine", value: "Fluphenazine" },
  { id: 399, name: "Flurandrenolide", value: "Flurandrenolide" },
  { id: 400, name: "Flurbiprofen", value: "Flurbiprofen" },
  { id: 401, name: "Flutamide", value: "Flutamide" },
  { id: 402, name: "Fluticasone", value: "Fluticasone" },
  { id: 403, name: "Fluvastatin", value: "Fluvastatin" },
  { id: 404, name: "Folic Acid", value: "Folic Acid" },
  { id: 405, name: "Foscarnet", value: "Foscarnet" },
  { id: 406, name: "Fosfomycin", value: "Fosfomycin" },
  { id: 407, name: "Furosemide Syrup 1%", value: "Furosemide Syrup 1%" },
  {
    id: 408,
    name: "Furosemide Injection 5%",
    value: "Furosemide Injection 5%",
  },
  { id: 409, name: "Disal®", value: "Disal®" },
  { id: 410, name: "Disal® Injection", value: "Disal® Injection" },
  { id: 411, name: "Salix® Tablets", value: "Salix® Tablets" },
  { id: 412, name: "Lasix® Syrup 1%", value: "Lasix® Syrup 1%" },
  { id: 413, name: "Lasix® Packets", value: "Lasix® Packets" },
  { id: 414, name: "Salix™ Injection 5%", value: "Salix™ Injection 5%" },
  { id: 415, name: "Furos-A-Vet", value: "Furos-A-Vet" },
  { id: 416, name: "Gabapentin", value: "Gabapentin" },
  { id: 417, name: "Gallium Nitrate", value: "Gallium Nitrate" },
  { id: 418, name: "Gemfibrozil", value: "Gemfibrozil" },
  { id: 419, name: "Gentamicin", value: "Gentamicin" },
  { id: 420, name: "Lantus", value: "Lantus" },
  { id: 421, name: "Glibenclamide", value: "Glibenclamide" },
  { id: 422, name: "Glyburide", value: "Glyburide" },
  { id: 423, name: "Glimepiride", value: "Glimepiride" },
  { id: 424, name: "Glipizide", value: "Glipizide" },
  { id: 425, name: "Glycerin", value: "Glycerin" },
  { id: 426, name: "Robinul®-V Injectable", value: "Robinul®-V Injectable" },
  {
    id: 427,
    name: "Glycopyrrolate Injectable",
    value: "Glycopyrrolate Injectable",
  },
  { id: 428, name: "Robinul®-V", value: "Robinul®-V" },
  { id: 429, name: "Gold Salts", value: "Gold Salts" },
  { id: 430, name: "CYSTORELIN®", value: "CYSTORELIN®" },
  { id: 431, name: "Fertelin™", value: "Fertelin™" },
  { id: 432, name: "OvaCyst™", value: "OvaCyst™" },
  { id: 433, name: "Griseofulvin Powder", value: "Griseofulvin Powder" },
  { id: 434, name: "Fulvicin U/F® Powder", value: "Fulvicin U/F® Powder" },
  { id: 435, name: "Grysio (Microsize)", value: "Grysio (Microsize)" },
  { id: 436, name: "Fulvicin U/F® Tablets", value: "Fulvicin U/F® Tablets" },
  {
    id: 437,
    name: "Fulvicin U/F® Bolus Veterinary",
    value: "Fulvicin U/F® Bolus Veterinary",
  },
  { id: 438, name: "Guanfacine", value: "Guanfacine" },
  { id: 439, name: "Intuniv®", value: "Intuniv®" },
  { id: 440, name: "Haloperidol", value: "Haloperidol" },
  { id: 441, name: "Heparin", value: "Heparin" },
  { id: 442, name: "Hyaluronidase", value: "Hyaluronidase" },
  { id: 443, name: "Hydralazine", value: "Hydralazine" },
  { id: 444, name: "Hydrochlorothiazide", value: "Hydrochlorothiazide" },
  { id: 445, name: "Hydrocortisone", value: "Hydrocortisone" },
  { id: 446, name: "Hydroxychloroquine", value: "Hydroxychloroquine" },
  { id: 447, name: "Hydroxyzine", value: "Hydroxyzine" },
  { id: 448, name: "Ibuprofen", value: "Ibuprofen" },
  { id: 449, name: "Idarubicin", value: "Idarubicin" },
  { id: 450, name: "Ifosfamide", value: "Ifosfamide" },
  { id: 451, name: "advantus™", value: "advantus™" },
  { id: 452, name: "Imipenem", value: "Imipenem" },
  { id: 453, name: "Imipramine", value: "Imipramine" },
  { id: 454, name: "Indapamide", value: "Indapamide" },
  { id: 455, name: "Indomethacin", value: "Indomethacin" },
  { id: 456, name: "ProZinc®", value: "ProZinc®" },
  { id: 457, name: "Interferon Alfa", value: "Interferon Alfa" },
  { id: 458, name: "Ipratropium", value: "Ipratropium" },
  { id: 459, name: "Iproniazid", value: "Iproniazid" },
  { id: 460, name: "Itrafungol®", value: "Itrafungol®" },
  {
    id: 461,
    name: "Ivermectin Chewable Tablets",
    value: "Ivermectin Chewable Tablets",
  },
  { id: 462, name: "Bimectin® Pour-On", value: "Bimectin® Pour-On" },
  { id: 463, name: "Equell®", value: "Equell®" },
  {
    id: 464,
    name: "Privermectin™ Equine Oral Liquid",
    value: "Privermectin™ Equine Oral Liquid",
  },
  { id: 465, name: "Bimectin®", value: "Bimectin®" },
  {
    id: 466,
    name: "Privermectin™ Drench for Sheep",
    value: "Privermectin™ Drench for Sheep",
  },
  { id: 467, name: "Privermectin®", value: "Privermectin®" },
  { id: 468, name: "Noromectin®", value: "Noromectin®" },
  { id: 469, name: "Ecomectin", value: "Ecomectin" },
  { id: 470, name: "Ivermectin Paste 1.87%", value: "Ivermectin Paste 1.87%" },
  { id: 471, name: "Ivermectin Injection", value: "Ivermectin Injection" },
  {
    id: 472,
    name: "Phoenectin® Paste 1.87%",
    value: "Phoenectin® Paste 1.87%",
  },
  {
    id: 473,
    name: "Bimectin® Injection for Cattle and Swine",
    value: "Bimectin® Injection for Cattle and Swine",
  },
  { id: 474, name: "Animect™ Plus", value: "Animect™ Plus" },
  { id: 475, name: "SparMectin-E", value: "SparMectin-E" },
  {
    id: 476,
    name: "Noromectin® Pour-On for Cattle",
    value: "Noromectin® Pour-On for Cattle",
  },
  {
    id: 477,
    name: "Heartgard® Chewables For Dogs",
    value: "Heartgard® Chewables For Dogs",
  },
  { id: 478, name: "Phoenectin®", value: "Phoenectin®" },
  {
    id: 479,
    name: "Ivomec® .27% Injection Grower And Feeder Pigs",
    value: "Ivomec® .27% Injection Grower And Feeder Pigs",
  },
  { id: 480, name: "Ivomec® Liquid", value: "Ivomec® Liquid" },
  { id: 481, name: "EQVALAN®", value: "EQVALAN®" },
  {
    id: 482,
    name: "Ivomec® Cattle Paste 0.153%",
    value: "Ivomec® Cattle Paste 0.153%",
  },
  {
    id: 483,
    name: "Heartgard 30®, Heartgard® Tablets",
    value: "Heartgard 30®, Heartgard® Tablets",
  },
  { id: 484, name: "Ivomec® Pour-On", value: "Ivomec® Pour-On" },
  { id: 485, name: "Iverhart™ Tablets", value: "Iverhart™ Tablets" },
  {
    id: 486,
    name: "Ivomec® Sustained-Release Bolus for Cattle",
    value: "Ivomec® Sustained-Release Bolus for Cattle",
  },
  { id: 487, name: "Heartgard® for Cats", value: "Heartgard® for Cats" },
  { id: 488, name: "Acarexx®", value: "Acarexx®" },
  { id: 489, name: "Zimecterin-EZ™", value: "Zimecterin-EZ™" },
  {
    id: 490,
    name: "Ivermectin Pour-On for Cattle, Phoenectin®",
    value: "Ivermectin Pour-On for Cattle, Phoenectin®",
  },
  {
    id: 491,
    name: "Ivomec® Premix for Swine",
    value: "Ivomec® Premix for Swine",
  },
  { id: 492, name: "Kanamycin", value: "Kanamycin" },
  { id: 493, name: "Ketamine", value: "Ketamine" },
  { id: 494, name: "Ketoconazole", value: "Ketoconazole" },
  { id: 495, name: "KETOFEN®", value: "KETOFEN®" },
  { id: 496, name: "KetoMed™", value: "KetoMed™" },
  { id: 497, name: "Ketorolac", value: "Ketorolac" },
  { id: 498, name: "L-Asparaginase", value: "L-Asparaginase" },
  { id: 499, name: "Lactulose", value: "Lactulose" },
  { id: 500, name: "Leuprolide", value: "Leuprolide" },
  {
    id: 501,
    name: "Totalon™ Topical Cattle Anthelmintic",
    value: "Totalon™ Topical Cattle Anthelmintic",
  },
  { id: 502, name: "Tramisol® Pour-On", value: "Tramisol® Pour-On" },
  { id: 503, name: "Levetiracetam", value: "Levetiracetam" },
  { id: 504, name: "Levobupivacaine", value: "Levobupivacaine" },
  { id: 505, name: "Levofloxacin", value: "Levofloxacin" },
  { id: 506, name: "Levonorgestrel", value: "Levonorgestrel" },
  { id: 507, name: "Levothyroxine", value: "Levothyroxine" },
  { id: 508, name: "Lidocaine", value: "Lidocaine" },
  { id: 509, name: "LINCOMIX® 20", value: "LINCOMIX® 20" },
  { id: 510, name: "LINCOMIX® 50", value: "LINCOMIX® 50" },
  {
    id: 511,
    name: "Lincomycin Injectable 30%",
    value: "Lincomycin Injectable 30%",
  },
  { id: 512, name: "LINCOMYCIN 100", value: "LINCOMYCIN 100" },
  { id: 513, name: "LINCOMYCIN 25", value: "LINCOMYCIN 25" },
  { id: 514, name: "LINCOMYCIN 300", value: "LINCOMYCIN 300" },
  {
    id: 515,
    name: "Lincomycin Injectable, USP",
    value: "Lincomycin Injectable, USP",
  },
  { id: 516, name: "Liothyronine", value: "Liothyronine" },
  { id: 517, name: "Lipase", value: "Lipase" },
  { id: 518, name: "Lisinopril", value: "Lisinopril" },
  { id: 519, name: "Lithium Carbonate", value: "Lithium Carbonate" },
  { id: 520, name: "Felimazole®", value: "Felimazole®" },
  { id: 521, name: "Versed", value: "Versed" },
  { id: 522, name: "Hypnovel", value: "Hypnovel" },
  { id: 523, name: "Robaxin®-V Injectable", value: "Robaxin®-V Injectable" },
  { id: 524, name: "Robaxin®-V Tablets", value: "Robaxin®-V Tablets" },
  { id: 525, name: "Methotrexate", value: "Methotrexate" },
  { id: 526, name: "Methoxyflurane", value: "Methoxyflurane" },
  { id: 527, name: "Medrol® Tablets", value: "Medrol® Tablets" },
  {
    id: 528,
    name: "Methylprednisolene Tablets",
    value: "Methylprednisolene Tablets",
  },
  { id: 529, name: "Metoclopramide", value: "Metoclopramide" },
  { id: 530, name: "AYRADIA™", value: "AYRADIA™" },
  { id: 531, name: "Cheque® Drops", value: "Cheque® Drops" },
  {
    id: 532,
    name: "Cheque® Medicated Dog Food",
    value: "Cheque® Medicated Dog Food",
  },
  { id: 533, name: "Micafungin", value: "Micafungin" },
  { id: 534, name: "Interceptor™", value: "Interceptor™" },
  { id: 535, name: "Sentinel", value: "Sentinel" },
  {
    id: 536,
    name: "Milbemite™ Otic Solution",
    value: "Milbemite™ Otic Solution",
  },
  { id: 537, name: "MilbeGuard™", value: "MilbeGuard™" },
  { id: 538, name: "Milrinone", value: "Milrinone" },
  { id: 539, name: "Mineral Oil", value: "Mineral Oil" },
  { id: 540, name: "Minocycline", value: "Minocycline" },
  { id: 541, name: "Mirataz®", value: "Mirataz®" },
  { id: 542, name: "Misoprostol", value: "Misoprostol" },
  { id: 543, name: "Mitotane", value: "Mitotane" },
  { id: 544, name: "Mitoxantrone", value: "Mitoxantrone" },
  { id: 545, name: "ProHeart™", value: "ProHeart™" },
  { id: 546, name: "Quest® Gel", value: "Quest® Gel" },
  {
    id: 547,
    name: "Cydectin™ (moxidectin) Pour-On for Beef and Dairy Cattle",
    value: "Cydectin™ (moxidectin) Pour-On for Beef and Dairy Cattle",
  },
  { id: 548, name: "ProHeart® 6", value: "ProHeart® 6" },
  { id: 549, name: "Cydectin®", value: "Cydectin®" },
  {
    id: 550,
    name: "Cydectin® Oral Drench for Sheep",
    value: "Cydectin® Oral Drench for Sheep",
  },
  { id: 551, name: "CORAXIS™", value: "CORAXIS™" },
  { id: 552, name: "ProHeart® 12", value: "ProHeart® 12" },
  { id: 553, name: "Tauramox™", value: "Tauramox™" },
  {
    id: 554,
    name: "Mupirocin Ointment USP, 2%",
    value: "Mupirocin Ointment USP, 2%",
  },
  { id: 555, name: "Bactoderm® Ointment", value: "Bactoderm® Ointment" },
  { id: 556, name: "Muricin™", value: "Muricin™" },
  { id: 557, name: "Mycophenolate Mofetil", value: "Mycophenolate Mofetil" },
  { id: 558, name: "N-acetylcysteine", value: "N-acetylcysteine" },
  { id: 559, name: "Nalbuphine", value: "Nalbuphine" },
  { id: 560, name: "Naloxone", value: "Naloxone" },
  { id: 561, name: "Equiproxen Granules", value: "Equiproxen Granules" },
  {
    id: 562,
    name: "Equiproxen 10% Solution",
    value: "Equiproxen 10% Solution",
  },
  { id: 563, name: "Neomycin", value: "Neomycin" },
  { id: 564, name: "Neostigmine", value: "Neostigmine" },
  { id: 565, name: "Nicardipine", value: "Nicardipine" },
  { id: 566, name: "Nifedipine", value: "Nifedipine" },
  { id: 567, name: "Nitazoxanide", value: "Nitazoxanide" },
  { id: 568, name: "Nitrofurantoin", value: "Nitrofurantoin" },
  { id: 569, name: "Nitroglycerin", value: "Nitroglycerin" },
  { id: 570, name: "Nitroprusside", value: "Nitroprusside" },
  { id: 571, name: "Norepinephrine", value: "Norepinephrine" },
  { id: 572, name: "Ofloxacin", value: "Ofloxacin" },
  { id: 573, name: "Olanzapine", value: "Olanzapine" },
  { id: 574, name: "GastroGard®", value: "GastroGard®" },
  { id: 575, name: "UlcerGard®", value: "UlcerGard®" },
  { id: 576, name: "Ondansetron", value: "Ondansetron" },
  { id: 577, name: "Tamiflu", value: "Tamiflu" },
  { id: 578, name: "Oxaliplatin", value: "Oxaliplatin" },
  { id: 579, name: "Oxybutynin", value: "Oxybutynin" },
  { id: 580, name: "Oxytocin Injection", value: "Oxytocin Injection" },
  {
    id: 581,
    name: "Oxytocin (Label Under Distributors)",
    value: "Oxytocin (Label Under Distributors)",
  },
  { id: 582, name: "Oxytocin Injectable", value: "Oxytocin Injectable" },
  {
    id: 583,
    name: "PVL Oxytocin Injectable",
    value: "PVL Oxytocin Injectable",
  },
  { id: 584, name: "Paclitaxel", value: "Paclitaxel" },
  { id: 585, name: "Paliperidone", value: "Paliperidone" },
  { id: 586, name: "Pancrelipase", value: "Pancrelipase" },
  { id: 587, name: "Pantoprazole", value: "Pantoprazole" },
  { id: 588, name: "Paroxetine", value: "Paroxetine" },
  { id: 589, name: "Peginterferon Alfa-b", value: "Peginterferon Alfa-b" },
  { id: 590, name: "Pemetrexed", value: "Pemetrexed" },
  { id: 591, name: "Penicillamine", value: "Penicillamine" },
  { id: 592, name: "Penicillin G", value: "Penicillin G" },
  { id: 593, name: "Pentobarbital", value: "Pentobarbital" },
  {
    id: 594,
    name: "Pentosan Polysulfate Sodium",
    value: "Pentosan Polysulfate Sodium",
  },
  { id: 595, name: "Permethrin", value: "Permethrin" },
  { id: 596, name: "FIDOQUEL™-CA1", value: "FIDOQUEL™-CA1" },
  { id: 597, name: "Phenoxybenzamine", value: "Phenoxybenzamine" },
  {
    id: 598,
    name: "Robizone Injectable 20%",
    value: "Robizone Injectable 20%",
  },
  { id: 599, name: "Bizolin® 1-G", value: "Bizolin® 1-G" },
  { id: 600, name: "Equipalazone", value: "Equipalazone" },
  { id: 601, name: "Butazolidin®", value: "Butazolidin®" },
  { id: 602, name: "Butazolidin® Paste", value: "Butazolidin® Paste" },
  { id: 603, name: "Bute", value: "Bute" },
  { id: 604, name: "Phenylbute™ Paste", value: "Phenylbute™ Paste" },
  { id: 605, name: "Phenylzone® Paste", value: "Phenylzone® Paste" },
  { id: 606, name: "Butatron Gel", value: "Butatron Gel" },
  {
    id: 607,
    name: "Phenylbutazone 20% Injection",
    value: "Phenylbutazone 20% Injection",
  },
  { id: 608, name: "Butequine™", value: "Butequine™" },
  { id: 609, name: "Superiorbute®", value: "Superiorbute®" },
  { id: 610, name: "Equizone 100™", value: "Equizone 100™" },
  {
    id: 611,
    name: "Phen-Buta-Vet Tablets, Phenylbutazone S/A",
    value: "Phen-Buta-Vet Tablets, Phenylbutazone S/A",
  },
  { id: 612, name: "Pributazone®", value: "Pributazone®" },
  {
    id: 613,
    name: "Phen-Buta-Vet Injection",
    value: "Phen-Buta-Vet Injection",
  },
  {
    id: 614,
    name: "Phenylbutazone Tablets, USP 100 mg",
    value: "Phenylbutazone Tablets, USP 100 mg",
  },
  {
    id: 615,
    name: "Phenylbutazone Tablets, USP 200 mg",
    value: "Phenylbutazone Tablets, USP 200 mg",
  },
  { id: 616, name: "Bizolin Injection 20%", value: "Bizolin Injection 20%" },
  {
    id: 617,
    name: "Butazolidin® Bolus, Butazolidin® Tablets",
    value: "Butazolidin® Bolus, Butazolidin® Tablets",
  },
  {
    id: 618,
    name: "Butazolidin® Injectable 20%",
    value: "Butazolidin® Injectable 20%",
  },
  { id: 619, name: "Butazolidin® Granules", value: "Butazolidin® Granules" },
  { id: 620, name: "Butatron®", value: "Butatron®" },
  { id: 621, name: "EquiBute Injection", value: "EquiBute Injection" },
  {
    id: 622,
    name: "EquiBute Tablets 100 mg",
    value: "EquiBute Tablets 100 mg",
  },
  { id: 623, name: "Tevcodyne Injectable", value: "Tevcodyne Injectable" },
  {
    id: 624,
    name: "Bizolin®-100, Bizolin®-200",
    value: "Bizolin®-100, Bizolin®-200",
  },
  {
    id: 625,
    name: "Phen-Buta Vet Tablets, Phenylbutazone Tablets (Horses)",
    value: "Phen-Buta Vet Tablets, Phenylbutazone Tablets (Horses)",
  },
  { id: 626, name: "Robizone-V", value: "Robizone-V" },
  {
    id: 627,
    name: "Phenylbutazone Tablets, USP 1 gram",
    value: "Phenylbutazone Tablets, USP 1 gram",
  },
  {
    id: 628,
    name: "Phen-Buta Vet Injection",
    value: "Phen-Buta Vet Injection",
  },
  { id: 629, name: "Phenylpropanolamine", value: "Phenylpropanolamine" },
  { id: 630, name: "Phenytoin", value: "Phenytoin" },
  { id: 631, name: "Vetmedin®-CA1", value: "Vetmedin®-CA1" },
  { id: 632, name: "Vetmedin®", value: "Vetmedin®" },
  { id: 633, name: "Vetmedin® Solution", value: "Vetmedin® Solution" },
  { id: 634, name: "Pindolol", value: "Pindolol" },
  { id: 635, name: "Piperacillin", value: "Piperacillin" },
  { id: 636, name: "Piperazine", value: "Piperazine" },
  { id: 637, name: "Polymyxin B", value: "Polymyxin B" },
  {
    id: 638,
    name: "Marquis® Antiprotozoal Oral Paste",
    value: "Marquis® Antiprotozoal Oral Paste",
  },
  { id: 639, name: "Posaconazole", value: "Posaconazole" },
  { id: 640, name: "Praziquantel Tablets", value: "Praziquantel Tablets" },
  { id: 641, name: "Prazi-C Tablets (OTC)", value: "Prazi-C Tablets (OTC)" },
  {
    id: 642,
    name: "Praziquantel Tablets (Rx)",
    value: "Praziquantel Tablets (Rx)",
  },
  { id: 643, name: "Praziquantel Injection", value: "Praziquantel Injection" },
  {
    id: 644,
    name: "Droncit® Canine Cestocide Tablets",
    value: "Droncit® Canine Cestocide Tablets",
  },
  {
    id: 645,
    name: "Droncit® Feline Cestocide Tablets",
    value: "Droncit® Feline Cestocide Tablets",
  },
  { id: 646, name: "Praziquantel 34 (Rx)", value: "Praziquantel 34 (Rx)" },
  {
    id: 647,
    name: "Tapeworm Dewormer for Cats (OTC)",
    value: "Tapeworm Dewormer for Cats (OTC)",
  },
  {
    id: 648,
    name: "Tapeworm Dewormer for Dogs (OTC)",
    value: "Tapeworm Dewormer for Dogs (OTC)",
  },
  {
    id: 649,
    name: "Droncit™ 5.68% Injectible Solution",
    value: "Droncit™ 5.68% Injectible Solution",
  },
  { id: 650, name: "Prazitech™", value: "Prazitech™" },
  { id: 651, name: "Prazosin", value: "Prazosin" },
  { id: 652, name: "PrednisTab®", value: "PrednisTab®" },
  { id: 653, name: "Meticorten®", value: "Meticorten®" },
  { id: 654, name: "Prilocaine", value: "Prilocaine" },
  { id: 655, name: "Procarbazine", value: "Procarbazine" },
  { id: 656, name: "Prochlorperazine", value: "Prochlorperazine" },
  { id: 657, name: "Promethazine", value: "Promethazine" },
  { id: 658, name: "PropoClear™", value: "PropoClear™" },
  { id: 659, name: "PropoFlo™", value: "PropoFlo™" },
  { id: 660, name: "PropoFlo™ 28", value: "PropoFlo™ 28" },
  { id: 661, name: "Rapanofal®", value: "Rapanofal®" },
  { id: 662, name: "Propranolol", value: "Propranolol" },
  { id: 663, name: "Protamine", value: "Protamine" },
  { id: 664, name: "Pyrantel", value: "Pyrantel" },
  { id: 665, name: "Pyridostigmine", value: "Pyridostigmine" },
  { id: 666, name: "Pyrimethamine", value: "Pyrimethamine" },
  { id: 667, name: "Quinidine", value: "Quinidine" },
  { id: 668, name: "Rabeprazole", value: "Rabeprazole" },
  { id: 669, name: "Ranitidine", value: "Ranitidine" },
  { id: 670, name: "Rifampin", value: "Rifampin" },
  { id: 671, name: "onsior™", value: "onsior™" },
  { id: 672, name: "onsior® injection", value: "onsior® injection" },
  {
    id: 673,
    name: "onsior® Tablets for Cats",
    value: "onsior® Tablets for Cats",
  },
  { id: 674, name: "Rosuvastatin", value: "Rosuvastatin" },
  { id: 675, name: "Roxithromycin", value: "Roxithromycin" },
  { id: 676, name: "Salbutamol", value: "Salbutamol" },
  { id: 677, name: "Salmeterol", value: "Salmeterol" },
  { id: 678, name: "Selamectin", value: "Selamectin" },
  { id: 679, name: "SelaSpot™", value: "SelaSpot™" },
  { id: 680, name: "Revolt®", value: "Revolt®" },
  { id: 681, name: "SENERGY™", value: "SENERGY™" },
  { id: 682, name: "Selarid®", value: "Selarid®" },
  { id: 683, name: "Revolution®", value: "Revolution®" },
  { id: 684, name: "Selegiline", value: "Selegiline" },
  { id: 685, name: "Sildenafil", value: "Sildenafil" },
  { id: 686, name: "Silver Sulfadiazine", value: "Silver Sulfadiazine" },
  { id: 687, name: "Simvastatin", value: "Simvastatin" },
  { id: 688, name: "Sirolimus", value: "Sirolimus" },
  { id: 689, name: "Sodium Bicarbonate", value: "Sodium Bicarbonate" },
  { id: 690, name: "Sodium Chloride", value: "Sodium Chloride" },
  { id: 691, name: "Sodium Phosphate", value: "Sodium Phosphate" },
  { id: 692, name: "Solifenacin", value: "Solifenacin" },
  { id: 693, name: "Comfortis®", value: "Comfortis®" },
  { id: 694, name: "Sucralfate", value: "Sucralfate" },
  { id: 695, name: "Sulfadiazine", value: "Sulfadiazine" },
  {
    id: 696,
    name: "Sulfadimethoxine Injection 40%",
    value: "Sulfadimethoxine Injection 40%",
  },
  {
    id: 697,
    name: "Sulfadimethoxine 12.5% Oral Solution",
    value: "Sulfadimethoxine 12.5% Oral Solution",
  },
  {
    id: 698,
    name: "Sulfadimethoxine Concentrated Solution 12.5%",
    value: "Sulfadimethoxine Concentrated Solution 12.5%",
  },
  {
    id: 699,
    name: "Sulfasol Soluble Powder",
    value: "Sulfasol Soluble Powder",
  },
  {
    id: 700,
    name: "Sulfadimethoxine Soluble Powder",
    value: "Sulfadimethoxine Soluble Powder",
  },
  { id: 701, name: "SulfaMed®", value: "SulfaMed®" },
  {
    id: 702,
    name: "Di-Methox Injection 40%",
    value: "Di-Methox Injection 40%",
  },
  { id: 703, name: "Sulfamed-G®", value: "Sulfamed-G®" },
  { id: 704, name: "DI-METHOX®", value: "DI-METHOX®" },
  { id: 705, name: "Sulforal®", value: "Sulforal®" },
  {
    id: 706,
    name: "Medacide-SDM Injection 10%",
    value: "Medacide-SDM Injection 10%",
  },
  {
    id: 707,
    name: "Albon® S.R. (Sustained Release)",
    value: "Albon® S.R. (Sustained Release)",
  },
  { id: 708, name: "Albon®", value: "Albon®" },
  {
    id: 709,
    name: "Albon Oral Suspension 5%",
    value: "Albon Oral Suspension 5%",
  },
  {
    id: 710,
    name: "Bactrovet Oral Suspension 12.5%",
    value: "Bactrovet Oral Suspension 12.5%",
  },
  { id: 711, name: "Albon® or Agribon®", value: "Albon® or Agribon®" },
  {
    id: 712,
    name: "AGRIBON® Concentrated Solution 12.5%, ALBON® Concentrated Solution 12.5%",
    value:
      "AGRIBON® Concentrated Solution 12.5%, ALBON® Concentrated Solution 12.5%",
  },
  { id: 713, name: "Albon® Tablets", value: "Albon® Tablets" },
  {
    id: 714,
    name: "Bactrovet Tablets 250 mg",
    value: "Bactrovet Tablets 250 mg",
  },
  { id: 715, name: "Sulfamethoxazole", value: "Sulfamethoxazole" },
  { id: 716, name: "Sulfasalazine", value: "Sulfasalazine" },
  { id: 717, name: "Sulindac", value: "Sulindac" },
  { id: 718, name: "Sunitinib", value: "Sunitinib" },
  { id: 719, name: "Tacrolimus", value: "Tacrolimus" },
  { id: 720, name: "Tadalafil", value: "Tadalafil" },
  { id: 721, name: "Tazobactam", value: "Tazobactam" },
  { id: 722, name: "Tegaserod", value: "Tegaserod" },
  { id: 723, name: "Semintra®", value: "Semintra®" },
  { id: 724, name: "Temozolomide", value: "Temozolomide" },
  { id: 725, name: "Temsirolimus", value: "Temsirolimus" },
  { id: 726, name: "Tenoxicam", value: "Tenoxicam" },
  { id: 727, name: "Terbinafine", value: "Terbinafine" },
  { id: 728, name: "Terbutaline", value: "Terbutaline" },
  { id: 729, name: "Teriparatide", value: "Teriparatide" },
  {
    id: 730,
    name: "Tetracycline Intramuscular Vet",
    value: "Tetracycline Intramuscular Vet",
  },
  { id: 731, name: "Thalidomide", value: "Thalidomide" },
  { id: 732, name: "Theophylline", value: "Theophylline" },
  { id: 733, name: "Thiabendazole", value: "Thiabendazole" },
  { id: 734, name: "Thiamine", value: "Thiamine" },
  { id: 735, name: "Thioctic Acid", value: "Thioctic Acid" },
  { id: 736, name: "Thiopental", value: "Thiopental" },
  { id: 737, name: "Thioridazine", value: "Thioridazine" },
  { id: 738, name: "Thiostrepton", value: "Thiostrepton" },
  { id: 739, name: "Thiotepa", value: "Thiotepa" },
  { id: 740, name: "Tilmovet® 90", value: "Tilmovet® 90" },
  { id: 741, name: "Tiotropium", value: "Tiotropium" },
  { id: 742, name: "Tipranavir", value: "Tipranavir" },
  { id: 743, name: "Toceranib", value: "Toceranib" },
  { id: 744, name: "Tolazoline", value: "Tolazoline" },
  { id: 745, name: "Tolbutamide", value: "Tolbutamide" },
  { id: 746, name: "Tinavet® Cream 1%", value: "Tinavet® Cream 1%" },
  { id: 747, name: "Toltrazuril", value: "Toltrazuril" },
  { id: 748, name: "Toremifene", value: "Toremifene" },
  { id: 749, name: "Tramadol", value: "Tramadol" },
  { id: 750, name: "Trandolapril", value: "Trandolapril" },
  { id: 751, name: "Trazodone", value: "Trazodone" },
  { id: 752, name: "Treprostinil", value: "Treprostinil" },
  { id: 753, name: "Triamcinolone", value: "Triamcinolone" },
  { id: 754, name: "Triamterene", value: "Triamterene" },
  { id: 755, name: "Triazolam", value: "Triazolam" },
  { id: 756, name: "Trichlormethiazide", value: "Trichlormethiazide" },
  { id: 757, name: "Trifluoperazine", value: "Trifluoperazine" },
  { id: 758, name: "Trifluridine", value: "Trifluridine" },
  { id: 759, name: "Triflusal", value: "Triflusal" },
  { id: 760, name: "VETORYL® CAPSULES", value: "VETORYL® CAPSULES" },
  { id: 761, name: "Trimethoprim", value: "Trimethoprim" },
  { id: 762, name: "Triptorelin", value: "Triptorelin" },
  { id: 763, name: "Tromethamine", value: "Tromethamine" },
  { id: 764, name: "Trospium", value: "Trospium" },
  { id: 765, name: "RESPIRmycin™", value: "RESPIRmycin™" },
  { id: 766, name: "Tulieve®", value: "Tulieve®" },
  { id: 767, name: "AROVYN™", value: "AROVYN™" },
  { id: 768, name: "TULAVEN™ 25", value: "TULAVEN™ 25" },
  { id: 769, name: "TULAVEN™ 100", value: "TULAVEN™ 100" },
  { id: 770, name: "Tulissin® 100", value: "Tulissin® 100" },
  {
    id: 771,
    name: "Draxxin® 25 Injectable Solution",
    value: "Draxxin® 25 Injectable Solution",
  },
  { id: 772, name: "Increxxa™", value: "Increxxa™" },
  { id: 773, name: "Increxxa™ 25", value: "Increxxa™ 25" },
  { id: 774, name: "MACROSYN™", value: "MACROSYN™" },
  { id: 775, name: "RESPIRmycin™ 25", value: "RESPIRmycin™ 25" },
  { id: 776, name: "Draxxin®", value: "Draxxin®" },
  { id: 777, name: "Tulissin® 25", value: "Tulissin® 25" },
  { id: 778, name: "BiloVet®", value: "BiloVet®" },
  { id: 779, name: "Tylan™ 200 Injection", value: "Tylan™ 200 Injection" },
  { id: 780, name: "Tylan™ 50 Injection", value: "Tylan™ 50 Injection" },
  {
    id: 781,
    name: "Tylovet® 200 mg/mL Injection",
    value: "Tylovet® 200 mg/mL Injection",
  },
  { id: 782, name: "Ursodiol", value: "Ursodiol" },
  { id: 783, name: "Valacyclovir", value: "Valacyclovir" },
  { id: 784, name: "Valganciclovir", value: "Valganciclovir" },
  { id: 785, name: "Vancomycin", value: "Vancomycin" },
  { id: 786, name: "Vardenafil", value: "Vardenafil" },
  { id: 787, name: "Vemurafenib", value: "Vemurafenib" },
  { id: 788, name: "Venlafaxine", value: "Venlafaxine" },
  { id: 789, name: "Verapamil", value: "Verapamil" },
  { id: 790, name: "Vigabatrin", value: "Vigabatrin" },
  { id: 791, name: "Vinblastine", value: "Vinblastine" },
  { id: 792, name: "Vincristine", value: "Vincristine" },
  { id: 793, name: "Vinorelbine", value: "Vinorelbine" },
  { id: 794, name: "Voriconazole", value: "Voriconazole" },
  { id: 795, name: "Warfarin", value: "Warfarin" },
  { id: 796, name: "XylaMed™", value: "XylaMed™" },
  { id: 797, name: "Xylitol", value: "Xylitol" },
  { id: 798, name: "Zafirlukast", value: "Zafirlukast" },
  { id: 799, name: "Zalcitabine", value: "Zalcitabine" },
  { id: 800, name: "Relenza", value: "Relenza" },
  { id: 801, name: "Zidovudine", value: "Zidovudine" },
  { id: 802, name: "Zilpaterol", value: "Zilpaterol" },
  { id: 803, name: "Zoledronic Acid", value: "Zoledronic Acid" },
  { id: 804, name: "Zonisamide", value: "Zonisamide" },
  { id: 805, name: "Zopiclone", value: "Zopiclone" },
  { id: 806, name: "Zuclopenthixol", value: "Zuclopenthixol" },
  { id: 807, name: "Domitor", value: "Domitor" },
  { id: 808, name: "Medetor", value: "Medetor" },
  { id: 809, name: "Yobine", value: "Yobine" },
  { id: 810, name: "Antagonil", value: "Antagonil" },
  { id: 811, name: "Robinul", value: "Robinul" },
  {
    id: 812,
    name: "Glycopyrrolate Injection",
    value: "Glycopyrrolate Injection",
  },
  { id: 813, name: "Xylocaine", value: "Xylocaine" },
  { id: 814, name: "Lidoderm", value: "Lidoderm" },
  { id: 815, name: "Epinephrine", value: "Epinephrine" },
  { id: 816, name: "Adrenalin", value: "Adrenalin" },
  { id: 817, name: "Telazol", value: "Telazol" },
  { id: 818, name: "Rimadyl", value: "Rimadyl" },
  { id: 819, name: "Metacam", value: "Metacam" },
  { id: 820, name: "Morphine", value: "Morphine" },
  { id: 821, name: "Normal Saline", value: "Normal Saline" },
  {
    id: 822,
    name: "Lactated Ringer's Solution",
    value: "Lactated Ringer's Solution",
  },
  { id: 823, name: "K-Dur", value: "K-Dur" },
  { id: 824, name: "Klor-Con", value: "Klor-Con" },
  { id: 825, name: "Kalcinate", value: "Kalcinate" },
  { id: 826, name: "Osmitrol", value: "Osmitrol" },
  { id: 827, name: "Glucose", value: "Glucose" },
  { id: 828, name: "Heparin Sodium", value: "Heparin Sodium" },
  { id: 829, name: "Phytonadione", value: "Phytonadione" },
  { id: 830, name: "Mephyton", value: "Mephyton" },
  { id: 831, name: "Forane", value: "Forane" },
  { id: 832, name: "IsoFlo", value: "IsoFlo" },
  { id: 833, name: "Ultane", value: "Ultane" },
  { id: 834, name: "SevoFlo", value: "SevoFlo" },
  { id: 835, name: "Diprivan", value: "Diprivan" },
  { id: 836, name: "Alfaxan", value: "Alfaxan" },
  { id: 837, name: "Atarax", value: "Atarax" },
  { id: 838, name: "Vistaril", value: "Vistaril" },
  { id: 839, name: "Chlor-Trimeton", value: "Chlor-Trimeton" },
  { id: 840, name: "Omnipen", value: "Omnipen" },
  { id: 841, name: "Polycillin", value: "Polycillin" },
  { id: 842, name: "Ancef", value: "Ancef" },
  { id: 843, name: "Kefzol", value: "Kefzol" },
  { id: 844, name: "Ery-Tab", value: "Ery-Tab" },
  { id: 845, name: "Eryc", value: "Eryc" },
  { id: 846, name: "Erythrocin", value: "Erythrocin" },
  { id: 847, name: "Tylan", value: "Tylan" },
  { id: 848, name: "Orbax", value: "Orbax" },
  { id: 849, name: "Veraflox", value: "Veraflox" },
  { id: 850, name: "Fucidin", value: "Fucidin" },
  { id: 851, name: "Nuflor", value: "Nuflor" },
  { id: 852, name: "Neo-Fradin", value: "Neo-Fradin" },
  { id: 853, name: "Polysporin", value: "Polysporin" },
  { id: 854, name: "Hibiclens", value: "Hibiclens" },
  { id: 855, name: "Nolvasan", value: "Nolvasan" },
  { id: 856, name: "Betadine", value: "Betadine" },
  { id: 857, name: "Diflucan", value: "Diflucan" },
  { id: 858, name: "Nizoral", value: "Nizoral" },
  { id: 859, name: "Lamisil", value: "Lamisil" },
  { id: 860, name: "Fungizone", value: "Fungizone" },
  { id: 861, name: "Famvir", value: "Famvir" },
  { id: 862, name: "Retrovir", value: "Retrovir" },
  { id: 863, name: "Bravecto", value: "Bravecto" },
  { id: 864, name: "NexGard", value: "NexGard" },
  { id: 865, name: "Capstar", value: "Capstar" },
  { id: 866, name: "Frontline", value: "Frontline" },
  { id: 867, name: "Vectra 3D", value: "Vectra 3D" },
  { id: 868, name: "Heartgard", value: "Heartgard" },
  { id: 869, name: "Iverhart", value: "Iverhart" },
  { id: 870, name: "Drontal", value: "Drontal" },
  { id: 871, name: "Droncit", value: "Droncit" },
  { id: 872, name: "Nemex", value: "Nemex" },
  { id: 873, name: "Comfortis", value: "Comfortis" },
  { id: 874, name: "Precor", value: "Precor" },
  { id: 875, name: "Archer", value: "Archer" },
  { id: 876, name: "Activyl", value: "Activyl" },
  { id: 877, name: "Panacur", value: "Panacur" },
  { id: 878, name: "Profender", value: "Profender" },
  { id: 879, name: "Immiticide", value: "Immiticide" },
  { id: 880, name: "Demadex", value: "Demadex" },
  { id: 881, name: "Norvasc", value: "Norvasc" },
  { id: 882, name: "Pseudoephedrine", value: "Pseudoephedrine" },
  { id: 883, name: "Premarin", value: "Premarin" },
];

export const MedicalSuppliments = [
  { id: 1, name: "Injectable Syringes", value: "Injectable Syringes" },
  { id: 2, name: "Hypodermic Needles", value: "Hypodermic Needles" },
  { id: 3, name: "Intravenous Catheters", value: "Intravenous Catheters" },
  { id: 4, name: "IV Fluid Bags", value: "IV Fluid Bags" },
  { id: 5, name: "Surgical Gloves", value: "Surgical Gloves" },
  { id: 6, name: "Sterile Surgical Drapes", value: "Sterile Surgical Drapes" },
  { id: 7, name: "Bandages", value: "Bandages" },
  { id: 8, name: "Gauze Pads", value: "Gauze Pads" },
  { id: 9, name: "Cotton Balls and Swabs", value: "Cotton Balls and Swabs" },
  { id: 10, name: "Suture Material", value: "Suture Material" },
  {
    id: 11,
    name: "Surgical Scalpel Blades and Handles",
    value: "Surgical Scalpel Blades and Handles",
  },
  { id: 12, name: "Blood Collection Tubes", value: "Blood Collection Tubes" },
  {
    id: 13,
    name: "Urine Collection Containers",
    value: "Urine Collection Containers",
  },
  { id: 14, name: "Fecal Test Kits", value: "Fecal Test Kits" },
  { id: 15, name: "X-ray Films", value: "X-ray Films" },
  { id: 16, name: "Ultrasound Gel", value: "Ultrasound Gel" },
  {
    id: 17,
    name: "Microscope Slides and Coverslips",
    value: "Microscope Slides and Coverslips",
  },
  { id: 18, name: "Medical Oxygen", value: "Medical Oxygen" },
];

export const frequencyList = [
  { name: "1-1-1", value: "1-1-1" },
  { name: "1-0-1", value: "1-0-1" },
  { name: "1-1-0", value: "1-1-0" },
  { name: "1-0-0", value: "1-0-0" },
  { name: "0-1-0", value: "0-1-0" },
  { name: "0-0-1", value: "0-0-1" },
  { name: "0-1-1", value: "0-1-1" },
];
